name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo test --locked
      - run: cargo clippy --locked -- -D warnings
      - run: cargo package --list --allow-dirty
